version: "3"

services:
  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  web:
    build: .
    command: python /usr/src/final_task/myapp/manage.py runserver ${ALLOWED_HOSTS}:${WEB_PORT}
    volumes:
      - myapp:/usr/src/final_task
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    env_file:
      - ./.env
    restart: on-failure
    depends_on:
      - redis
  celery:
    build: .
    command: bash -c "cd myapp && celery -A myapp worker -l INFO --pool=solo"
    volumes:
      - myapp:/usr/src/final_task
    env_file:
      - ./.env
    restart: on-failure
    depends_on:
      - redis
      - web
  celery-beat:
    build: .
    command: bash -c "cd myapp && celery -A myapp beat"
    env_file:
      - ./.env
    volumes:
      - myapp:/usr/src/final_task
    restart: on-failure
    depends_on:
      - redis
      - web
volumes:
  myapp: