version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build: .
    environment:
      - REDIS_HOST=redis
    command: python /usr/src/rest_service/myapp/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/rest_service/
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - redis
  celery:
    build: .
    command: bash -c "cd myapp && celery -A myapp worker -l INFO --pool=solo"
    volumes:
      - .:/usr/src/rest_service/
    restart: on-failure
    depends_on:
      - redis
      - web
  celery-beat:
    build: .
    command: bash -c "cd myapp && celery -A myapp beat"
    volumes:
      - .:/usr/src/rest_service/
    restart: on-failure
    depends_on:
      - redis
      - web