# Generated by Django 3.2.4 on 2021-06-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathercity',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
