# Generated by Django 3.2.4 on 2021-06-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topcities',
            name='city',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
