# Generated by Django 3.2.4 on 2021-06-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
